### ISSUE TITLE
I need the covert channel dataset

### ISSUE THREAD

**Issue by james1-cpu** [MdAhsanAyub/NetworkCovertChannel#1]
Hello,Dear Mr, I'm soory to bother you at this time. I am a investigator of covert channel and I'm very interested  in your paper-A Protocol Independent Approach in Network. I want to contiue  my research  based your achievement,but I don't have your experiment dataset which casuing a  diffcult probelm to me. I will be rally grateful if you can share your covert chaneel dataset used in your paper.I think this dataset is very helpful to my research. 
       filnally,expressing my sincerely gratitude to you again.

**Comment by AhsanAyub** [comment]
Hello, thanks for showing interest in our research. I would be very much happy to share the datasets that we used with you. Please share your email address, and I will share a sharable link of the dataset with you. Thanks again!

**Comment by james1-cpu** [comment]
I'm very excited to receive  your reply. my email address is 987367871@qq.com. Thanks you for  sharing your dataset to me.The best wish to you.

**Comment by AhsanAyub** [comment]
Hi, I have sent you an email to share the dataset with you. Hope it helps, thank you!

**Comment by james1-cpu** [comment]
> Hi, I have sent you an email to share the dataset with you. Hope it helps, thank you!

Ok,I have acquired you dataset form the email that your sent to me.Thank you very much!
